env:
  browser: true
  es6: true
  node: true
parser: babel-eslint
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  strict: 1
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
