sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - ANSIBLE=2.4
  - ANSIBLE=2.5
matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: ANSIBLE=2.2
    - python: "2.7"
      env: ANSIBLE=2.3
install: pip install tox-travis
script:
  - tox
